<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "jv_events"
 *
 * Auto generated by Extension Builder 2016-09-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Eventmanagement',
	'description' => 'List and show Events with filters. Including registration',
	'category' => 'plugin',
	'author' => 'Jörg Velletti',
	'author_email' => 'typo3@velletti.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.1.5',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'static_info_tables' => '0.0.0-99.99.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);