services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  JVelletti\JvEvents\:
    resource: '../Classes/*'

  JVelletti\JvEvents\Command\UpdateSlugCommand:
    tags:
      - name: 'console.command'
        command: 'jvevents:updateslug'
        schedulable: true
  JVelletti\JvEvents\Command\UsergroupCommand:
    tags:
      - name: 'console.command'
        command: 'jvevents:usergroup'
        schedulable: false