
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false



  JVelletti\JvEvents\Command\:
    resource: '../Classes/Command/*'

  JVelletti\JvEvents\Scheduler\:
    resource: '../Classes/Scheduler/*'

  JVelletti\JvEvents\Event\:
    resource: '../Classes/Event/*'

  JVelletti\JvEvents\Middleware\:
    resource: '../Classes/Middleware/*'



  JVelletti\JvEvents\Command\UpdateSlugCommand:
    tags:
      - name: 'console.command'
        command: 'jvevents:updateslug'
        schedulable: true
  JVelletti\JvEvents\Command\UsergroupCommand:
    tags:
      - name: 'console.command'
        command: 'jvevents:usergroup'
        schedulable: false
  JVelletti\JvEvents\Command\CleanupMissingFilesCommand:
    tags:
      - name: 'console.command'
        command: 'jvevents:missingfiles'
        schedulable: false